/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.realyusufismail

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class JconfigPluginPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create("jconfig", JGradleConfig::class.java)

        project.tasks.register("jconfigTask", JconfigTask::class.java) { task ->
            task.config = project.extensions.getByType(JGradleConfig::class.java)
        }
    }
}
