/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.realyusufismail

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test for the 'io.github.realyusufismail.jconfig-plugin' plugin.
 */
class JConfigPluginPluginPluginFunctionalTest {

    @TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle.kts") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle.kts") }

    @Test
    fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id("io.github.realyusufismail.jconfig-plugin")
            }
        """.trimIndent())

        // Create a temporary config.json file
        val configFile = File(projectDir, "config.json")
        println("Config file path: ${configFile.absolutePath}")
        configFile.writeText(
            """
        {
            "key1": "value1",
            "key2": "value2"
        }
        """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("jconfigTask")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("BUILD SUCCESSFUL"))
    }
}