/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.realyusufismail

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple functional test for the 'io.github.realyusufismail.jconfig-plugin' plugin.
 */
class JConfigPluginPluginFunctionalTest {

    @Test fun `can run task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.realyusufismail.jconfig-plugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("jconfigTask"))
    }
}